config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :beans

end

app/models/bean.rb
class Bean < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beans_controller.rb
class BeansController < ApplicationController
  before_action :set_bean, only: [:show, :edit, :update, :destroy]

  def index
    @beans= Bean.all
  end

  def new
    @bean=Bean.new
  end

  def create
    @bean = Bean.new(bean_params)
    if @bean.save
      redirect_to beans_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @bean.update
    redirect_to bean_path(@bean)
  end

  def destroy
    @bean.destroy
  end

  private

  def set_bean
    @bean=Bean.find(params[:id])
  end

  def bean_params
    params.require(:bean).permit(:species, :date_planted, :date_harvested)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beans/_form.html.erb
<h1> NEW BEAN! </h1>

<%= form_for @bean do |b| %>

<%= b.label :species %>
<%= b.text_field :species %>

<%= b.label :date_planted %>
<%= b.date_field :date_planted %>

<%= b.label :date_harvested %>
<%= b.date_field :date_harvested %>

<%= b.submit %>

<% end %>

app/views/beans/edit.html.erb
<h1> EDITING CHYOUR BEANZ </h1>

<%= render "form" %>

<%= link_to "Cancel", beans_path %>

app/views/beans/index.html.erb
<%= link_to "NEW BEAN!!!", new_bean_path %>
<%= @beans.each do |b| %>

<%= link_to b.type, bean_path(b) %>
</br>
<%= b.date_planted%>
</br>
<%= b.date_harvested %>
</br>
<%= link_to "Edit", edit_bean_path(@bean) %> | <%= link_to "Destroy BEAN!!", bean_path(@bean), method: :delete %>
<% end %>

app/views/beans/new.html.erb
<h1> NEW BEAN!! </h1>

<%= render "form" %>

app/views/beans/show.html.erb
<h1> THE BEAN YOU'VE SELECTED: </h1>

<%= @bean.type %>
</br>
<%= @bean.date_planted %>
</br>
<%= @bean.date_harvested %>

<%= link_to "Edit", edit_bean_path(@bean) %> | <%= link_to "Cancel", beans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeansCrudPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1> Welcome to My Beans Page!!!!!</h1>
</br>
<%= link_to "New Bean", new_bean_path %>
</br>
<%= link_to "BEAANNNSS!!!", beans_path %>